# DropWizard
server:
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: DEBUG
  loggers:
    io.netty: INFO
    org.eclipse.jetty: INFO
    reactor.netty: INFO
  appenders:
    - type: console
      logFormat: "%d{yyyy-MM-dd HH:mm:ss} [%level][%X{ctx}][%logger{36}] - [%msg]%n"
      timeZone: America/New_York

tenant:
  tenantUrl: "${TENANT_URL}"
  svcAcctId: "${SVCACCT_ID}"
  svcAcctKeyPath: "${SVCACCT_KEYPATH}"